<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">    
    <title><?=SITE_TITLE?></title>      
    <link href="<?=assets('libs/font-awesome-4.7.0/css/font-awesome.min.css')?>" rel="stylesheet" media="all">            
    <link href="<?=assets('libs/bootstrap-3.3.7-dist/css/bootstrap.min.css')?>" rel="stylesheet" media="all">            
    <link href="<?=assets('css/style.css', true)?>" rel="stylesheet" media="all">
                 
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->     
</head>
<body>    

<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<?=URL?>/">PHP-DROPBOX</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="<?=URL?>/?p=home">Home</a></li>
      <li><a href="<?=URL?>/?p=arquivos">Arquivos</a></li>      
    </ul>

    <ul class="nav navbar-nav navbar-right">      
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=usuario_logado()?> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="<?=URL?>/sair">Sair</a></li>          
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

  <div class="container">  
    
    <div class="conteudo-paginas">
      <?=System\Page::loads($page, System\Config::getDefaultRouter());?>
    </div>     

  </div>  
    
   
  <script src="<?=assets('libs/jquery/jquery-1.12.1.min.js')?>"></script>  
  <script src="<?=assets('libs/bootstrap-3.3.7-dist/js/bootstrap.min.js')?>"></script>  
  <script src="<?=assets('js/script.js', true)?>"></script>
</body>
</html>